CREATE TABLE `data_platform_delivery_document_header_data`
(
    `DeliveryDocument`                         int(16) NOT NULL,
    `DeliveryDocumentDate`                     date NOT NULL,
    `SupplyChainRelationshipID`                int(16) NOT NULL,
    `SupplyChainRelationshipDeliveryID`        int(6) NOT NULL,
    `SupplyChainRelationshipDeliveryPlantID`   int(4) NOT NULL,
    `SupplyChainRelationshipBillingID`         int(4) DEFAULT NULL,
    `SupplyChainRelationshipPaymentID`         int(2) DEFAULT NULL,
    `SupplyChainRelationshipFreightID`         int(4) DEFAULT NULL,
    `Buyer`                                    int(12) NOT NULL,
    `Seller`                                   int(12) NOT NULL,
    `DeliverToParty`                           int(12) NOT NULL,
    `DeliverFromParty`                         int(12) NOT NULL,
    `DeliverToPlant`                           varchar(4) NOT NULL,
    `DeliverFromPlant`                         varchar(4) NOT NULL,
    `BillToParty`                              int(12) DEFAULT NULL,
    `BillFromParty`                            int(12) DEFAULT NULL,
    `BillToCountry`                            varchar(3) DEFAULT NULL,
    `BillFromCountry`                          varchar(3) DEFAULT NULL,
    `Payer`                                    int(12) DEFAULT NULL,
    `Payee`                                    int(12) DEFAULT NULL,
    `FreightPartner`                           int(12) DEFAULT NULL,
    `IsExportImport`                           tinyint(1) DEFAULT NULL,
    `DeliverToPlantTimeZone`                   varchar(3) DEFAULT NULL,
    `DeliverFromPlantTimeZone`                 varchar(3) DEFAULT NULL,
    `ReferenceDocument`                        int(16) DEFAULT NULL,
    `ReferenceDocumentItem`                    int(6) DEFAULT NULL,
    `OrderID`                                  int(16) DEFAULT NULL,
    `OrderItem`                                int(6) DEFAULT NULL,
    `Contract`                                 int(16) DEFAULT NULL,
    `ContractItem`                             int(6) DEFAULT NULL,
    `ProductionVersion`                        int(16) DEFAULT NULL,
    `ProductionVersionItem`                    int(6) DEFAULT NULL,
    `ProductionOrder`                          int(16) DEFAULT NULL,
    `ProductionOrderItem`                      int(6) DEFAULT NULL,
    `Operations`                               int(16) DEFAULT NULL,
    `OperationsItem`                           int(6) DEFAULT NULL,
    `OperationID`                              int(4) DEFAULT NULL,
    `BillOfMaterial`                           int(16) DEFAULT NULL,
    `BillOfMaterialItem`                       int(6) DEFAULT NULL,
    `ContractType`                             varchar(4) DEFAULT NULL,
    `OrderValidityStartDate`                   date DEFAULT NULL,
    `OrderValidityEndDate`                     date DEFAULT NULL,
    `PlannedGoodsIssueDate`                    date NOT NULL,
    `PlannedGoodsIssueTime`                    time NOT NULL,
    `PlannedGoodsReceiptDate`                  date NOT NULL,
    `PlannedGoodsReceiptTime`                  time NOT NULL,
    `FreightOrder`                             int(16) DEFAULT NULL,
    `InvoiceDocumentDate`                      date DEFAULT NULL,
    `HeaderCompleteDeliveryIsDefined`          tinyint(1) DEFAULT NULL,
    `HeaderDeliveryStatus`                     varchar(2) DEFAULT NULL,
    `GoodsIssueOrReceiptSlipNumber`            varchar(35) DEFAULT NULL,
    `HeaderBillingStatus`                      varchar(2) DEFAULT NULL,
    `HeaderBillingConfStatus`                  varchar(2) DEFAULT NULL,
    `HeaderBillingBlockStatus`                 tinyint(1) DEFAULT NULL,
    `HeaderGrossWeight`                        float(15) DEFAULT NULL,
    `HeaderNetWeight`                          float(15) DEFAULT NULL,
    `HeaderWeightUnit`                         varchar(3) DEFAULT NULL,
    `Incoterms`                                varchar(3) DEFAULT NULL,
    `TransactionCurrency`                      varchar(5) DEFAULT NULL,
    `HeaderDeliveryBlockStatus`                tinyint(1) DEFAULT NULL,
    `HeaderIssuingBlockStatus`                 tinyint(1) DEFAULT NULL,
    `HeaderReceivingBlockStatus`               tinyint(1) DEFAULT NULL,
    `ExternalReferenceDocument`                varchar(100) DEFAULT NULL,
    `CertificateAuthorityChain`                varchar(2000) DEFAULT NULL,
    `UsageControlChain`                        varchar(2000) DEFAULT NULL,
    `CreationDate`                             date NOT NULL,
    `CreationTime`                             time NOT NULL,
    `LastChangeDate`                           date NOT NULL,
    `LastChangeTime`                           time NOT NULL,
    `IsCancelled`                              tinyint(1) DEFAULT NULL,
    `IsMarkedForDeletion`                      tinyint(1) DEFAULT NULL,
    
    PRIMARY KEY (`DeliveryDocument`),

    CONSTRAINT `DPFMDeliveryDocumentHeaderDataSCRDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_scr_delivery_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataSCRDeliveryPlantID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`) REFERENCES `data_platform_scr_delivery_plant_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataSCRBillingID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`) REFERENCES `data_platform_scr_billing_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataSCRPaymentID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`) REFERENCES `data_platform_scr_payment_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataSCRFreightID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `SupplyChainRelationshipFreightID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `FreightPartner`) REFERENCES `data_platform_scr_freight_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `SupplyChainRelationshipFreightID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `FreightPartner`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataBillToCountry_fk` FOREIGN KEY (`BillToCountry`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataBillFromCountry_fk` FOREIGN KEY (`BillFromCountry`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataOrderItem_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataContract_fk` FOREIGN KEY (`Contract`) REFERENCES `data_platform_contract_header_data` (`Contract`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataContractItem_fk` FOREIGN KEY (`Contract`, `ContractItem`) REFERENCES `data_platform_contract_item_data` (`Contract`, `ContractItem`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataProductionVersionItem_fk` FOREIGN KEY (`ProductionVersion`, `ProductionVersionItem`) REFERENCES `data_platform_production_version_item_data` (`ProductionVersion`, `ProductionVersionItem`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataProductionOrderItem_fk` FOREIGN KEY (`ProductionOrder`, `ProductionOrderItem`) REFERENCES `data_platform_production_order_item_data` (`ProductionOrder`, `ProductionOrderItem`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataProductionOrderItemOperation_fk` FOREIGN KEY (`ProductionOrder`, `ProductionOrderItem`, `Operations`, `OperationsItem`, `OperationID`) REFERENCES `data_platform_production_order_item_operation_data` (`ProductionOrder`, `ProductionOrderItem`, `Operations`, `OperationsItem`, `OperationID`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataBillOfMaterial_fk` FOREIGN KEY (`BillOfMaterial`, `BillOfMaterialItem`) REFERENCES `data_platform_bill_of_material_item_data` (`BillOfMaterial`, `BillOfMaterialItem`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataDeliverToPlantTimeZone_fk` FOREIGN KEY (`DeliverToPlantTimeZone`) REFERENCES `data_platform_time_zone_time_zone_data` (`TimeZone`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataDeliverFromPlantTimeZone_fk` FOREIGN KEY (`DeliverFromPlantTimeZone`) REFERENCES `data_platform_time_zone_time_zone_data` (`TimeZone`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataFreightOrder_fk` FOREIGN KEY (`FreightOrder`) REFERENCES `data_platform_freight_order_header_data` (`FreightOrder`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataHeaderWeightUnit_fk` FOREIGN KEY (`HeaderWeightUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataIncoterms_fk` FOREIGN KEY (`Incoterms`) REFERENCES `data_platform_incoterms_incoterms_data` (`Incoterms`),
    CONSTRAINT `DPFMDeliveryDocumentHeaderDataTransactionCurrency_fk` FOREIGN KEY (`TransactionCurrency`) REFERENCES `data_platform_currency_currency_data` (`Currency`)
    
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
