CREATE TABLE `data_platform_delivery_document_item_data`
(
    `DeliveryDocument`                                int(16) NOT NULL,
    `DeliveryDocumentItem`                            int(6) NOT NULL,
    `DeliveryDocumentItemCategory`                    varchar(4) NOT NULL,
    `SupplyChainRelationshipID`                       int(16) NOT NULL,
    `SupplyChainRelationshipDeliveryID`               int(6) NOT NULL,
    `SupplyChainRelationshipDeliveryPlantID`          int(4) NOT NULL,
    `SupplyChainRelationshipStockConfPlantID`         int(4) NOT NULL,
    `SupplyChainRelationshipProductionPlantID`        int(4) NOT NULL,
    `SupplyChainRelationshipBillingID`                int(4) DEFAULT NULL,
    `SupplyChainRelationshipPaymentID`                int(2) DEFAULT NULL,
    `Buyer`                                           int(12) NOT NULL,
    `Seller`                                          int(12) NOT NULL,
    `DeliverToParty`                                  int(12) NOT NULL,
    `DeliverFromParty`                                int(12) NOT NULL,
    `DeliverToPlant`                                  varchar(4) NOT NULL,
    `DeliverFromPlant`                                varchar(4) NOT NULL,
    `BillToParty`                                     int(12) DEFAULT NULL,
    `BillFromParty`                                   int(12) DEFAULT NULL,
    `BillToCountry`                                   varchar(3) DEFAULT NULL,
    `BillFromCountry`                                 varchar(3) DEFAULT NULL,
    `Payer`                                           int(12) DEFAULT NULL,
    `Payee`                                           int(12) DEFAULT NULL,
    `Product`                                         varchar(40) NOT NULL,
    `ProductStandardID`                               varchar(18) DEFAULT NULL,
    `ProductGroup`                                    varchar(9) DEFAULT NULL,
    `BaseUnit`                                        varchar(3) NOT NULL,
    `DeliveryUnit`                                    varchar(3) NOT NULL,
    `OriginalQuantityInBaseUnit`                      float(15) NOT NULL,
    `OriginalQuantityInDeliveryUnit`                  float(15) NOT NULL,
    `DeliverToPlantStorageLocation`                   varchar(4) DEFAULT NULL,
    `ProductIsBatchManagedInDeliverToPlant`           tinyint(1) DEFAULT NULL,
    `BatchMgmtPolicyInDeliverToPlant`                 varchar(4) DEFAULT NULL,
    `DeliverToPlantBatch`                             varchar(10) DEFAULT NULL,
    `DeliverToPlantBatchValidityStartDate`            date DEFAULT NULL,
    `DeliverToPlantBatchValidityStartTime`            time DEFAULT NULL,
    `DeliverToPlantBatchValidityEndDate`              date DEFAULT NULL,
    `DeliverToPlantBatchValidityEndTime`              time DEFAULT NULL,
    `DeliverFromPlantStorageLocation`                 varchar(4) DEFAULT NULL,
    `ProductIsBatchManagedInDeliverFromPlant`         tinyint(1) DEFAULT NULL,
    `BatchMgmtPolicyInDeliverFromPlant`               varchar(4) DEFAULT NULL,
    `DeliverFromPlantBatch`                           varchar(10) DEFAULT NULL,
    `DeliverFromPlantBatchValidityStartDate`          date DEFAULT NULL,
    `DeliverFromPlantBatchValidityStartTime`          time DEFAULT NULL,
    `DeliverFromPlantBatchValidityEndDate`            date DEFAULT NULL,
    `DeliverFromPlantBatchValidityEndTime`            time DEFAULT NULL,
    `StockConfirmationBusinessPartner`                int(12) NOT NULL,
    `StockConfirmationPlant`                          varchar(4) NOT NULL,
    `ProductIsBatchManagedInStockConfirmationPlant`   tinyint(1) DEFAULT NULL,
    `BatchMgmtPolicyInStockConfirmationPlant`         varchar(4) DEFAULT NULL,
    `StockConfirmationPlantBatch`                     varchar(10) DEFAULT NULL,
    `StockConfirmationPlantBatchValidityStartDate`    date DEFAULT NULL,
    `StockConfirmationPlantBatchValidityStartTime`    time DEFAULT NULL,
    `StockConfirmationPlantBatchValidityEndDate`      date DEFAULT NULL,
    `StockConfirmationPlantBatchValidityEndTime`      time DEFAULT NULL,
    `StockConfirmationPolicy`                         varchar(4) DEFAULT NULL,
    `StockConfirmationStatus`                         varchar(2) DEFAULT NULL,
    `ProductionPlantBusinessPartner`                  int(12) DEFAULT NULL,
    `ProductionPlant`                                 varchar(4) DEFAULT NULL,
    `ProductionPlantStorageLocation`                  varchar(4) DEFAULT NULL,
    `ProductIsBatchManagedInProductionPlant`          tinyint(1) DEFAULT NULL,
    `BatchMgmtPolicyInProductionPlant`                varchar(4) DEFAULT NULL,
    `ProductionPlantBatch`                            varchar(10) DEFAULT NULL,
    `ProductionPlantBatchValidityStartDate`           date DEFAULT NULL,
    `ProductionPlantBatchValidityStartTime`           time DEFAULT NULL,
    `ProductionPlantBatchValidityEndDate`             date DEFAULT NULL,
    `ProductionPlantBatchValidityEndTime`             time DEFAULT NULL,
    `InspectionPlan`                                  int(16) DEFAULT NULL,
    `InspectionPlant`                                 varchar(4) DEFAULT NULL,
    `InspectionOrder`                                 int(16) DEFAULT NULL,
    `DeliveryDocumentItemText`                        varchar(200) DEFAULT NULL,
    `DeliveryDocumentItemTextByBuyer`                 varchar(200) NOT NULL,
    `DeliveryDocumentItemTextBySeller`                varchar(200) NOT NULL,
    `PlannedGoodsIssueDate`                           date NOT NULL,
    `PlannedGoodsIssueTime`                           time NOT NULL,
    `PlannedGoodsReceiptDate`                         date NOT NULL,
    `PlannedGoodsReceiptTime`                         time NOT NULL,
    `PlannedGoodsIssueQuantity`                       float(15) NOT NULL,
    `PlannedGoodsIssueQtyInBaseUnit`                  float(15) NOT NULL,
    `PlannedGoodsReceiptQuantity`                     float(15) NOT NULL,
    `PlannedGoodsReceiptQtyInBaseUnit`                float(15) NOT NULL,
    `ActualGoodsIssueDate`                            date DEFAULT NULL,
    `ActualGoodsIssueTime`                            time DEFAULT NULL,
    `ActualGoodsReceiptDate`                          date DEFAULT NULL,
    `ActualGoodsReceiptTime`                          time DEFAULT NULL,
    `ActualGoodsIssueQuantity`                        float(15) DEFAULT NULL,
    `ActualGoodsIssueQtyInBaseUnit`                   float(15) DEFAULT NULL,
    `ActualGoodsReceiptQuantity`                      float(15) DEFAULT NULL,
    `ActualGoodsReceiptQtyInBaseUnit`                 float(15) DEFAULT NULL,
    `QuantityPerPackage`                              float(15) DEFAULT NULL,
    `ItemBillingStatus`                               varchar(2) DEFAULT NULL,
    `ItemCompleteDeliveryIsDefined`                   tinyint(1) DEFAULT NULL,
    `ItemWeightUnit`                                  varchar(3) DEFAULT NULL,
    `ItemNetWeight`                                   float(13) DEFAULT NULL,
    `ItemGrossWeight`                                 float(13) DEFAULT NULL,
    `InternalCapacityQuantity`                        float(15) DEFAULT NULL,
    `InternalCapacityQuantityUnit`                    varchar(3) DEFAULT NULL,
    `ItemIsBillingRelevant`                           tinyint(1) DEFAULT NULL,
    `NetAmount`                                       float(13) DEFAULT NULL,
    `TaxAmount`                                       float(13) DEFAULT NULL,
    `GrossAmount`                                     float(13) DEFAULT NULL,
    `OrderID`                                         int(16) DEFAULT NULL,
    `OrderItem`                                       int(6) DEFAULT NULL,
    `ProductionOrder`                                 int(16) DEFAULT NULL,
    `ProductionOrderItem`                             int(6) DEFAULT NULL,
    `BillOfMaterial`                                  int(16) DEFAULT NULL,
    `BillOfMaterialItem`                              int(6) DEFAULT NULL,
    `Operations`                                      int(16) DEFAULT NULL,
    `OperationsItem`                                  int(6) DEFAULT NULL,
    `OrderType`                                       varchar(3) DEFAULT NULL,
    `ContractType`                                    varchar(4) DEFAULT NULL,
    `OrderValidityStartDate`                          date DEFAULT NULL,
    `OrderValidityEndDate`                            date DEFAULT NULL,
    `PaymentTerms`                                    varchar(4) DEFAULT NULL,
    `DueCalculationBaseDate`                          date DEFAULT NULL,
    `PaymentDueDate`                                  date DEFAULT NULL,
    `NetPaymentDays`                                  int(3) DEFAULT NULL,
    `PaymentMethod`                                   varchar(1) DEFAULT NULL,
    `InvoicePeriodStartDate`                          date DEFAULT NULL,
    `InvoicePeriodEndDate`                            date DEFAULT NULL,
    `ConfirmedDeliveryDate`                           date DEFAULT NULL,
    `Project`                                         int(16) DEFAULT NULL,
    `WBSElement`                                      int(8) DEFAULT NULL,
    `ReferenceDocument`                               int(16) DEFAULT NULL,
    `ReferenceDocumentItem`                           int(6) DEFAULT NULL,
    `TransactionTaxClassification`                    varchar(1) NOT NULL,
    `ProductTaxClassificationBillToCountry`           varchar(1) NOT NULL,
    `ProductTaxClassificationBillFromCountry`         varchar(1) NOT NULL,
    `DefinedTaxClassification`                        varchar(1) NOT NULL,
    `AccountAssignmentGroup`                          varchar(2) NOT NULL,
    `ProductAccountAssignmentGroup`                   varchar(2) NOT NULL,
    `TaxCode`                                         varchar(2) DEFAULT NULL,
    `TaxRate`                                         float(6) DEFAULT NULL,
    `CountryOfOrigin`                                 varchar(3) DEFAULT NULL,
    `CountryOfOriginLanguage`                         varchar(2) DEFAULT NULL,
    `Equipment`                                       int(20) DEFAULT NULL,
    `ItemDeliveryBlockStatus`                         tinyint(1) DEFAULT NULL,
    `ItemIssuingBlockStatus`                          tinyint(1) DEFAULT NULL,
    `ItemReceivingBlockStatus`                        tinyint(1) DEFAULT NULL,
    `ItemBillingBlockStatus`                          tinyint(1) DEFAULT NULL,
    `ExternalReferenceDocument`                       varchar(100) DEFAULT NULL,
    `ExternalReferenceDocumentItem`                   varchar(10) DEFAULT NULL,
    `CreationDate`                                    date NOT NULL,
    `CreationTime`                                    time NOT NULL,
    `LastChangeDate`                                  date NOT NULL,
    `LastChangeTime`                                  time NOT NULL, 
    `IsCancelled`                                     tinyint(1) DEFAULT NULL,
    `IsMarkedForDeletion`                             tinyint(1) DEFAULT NULL,
    
    PRIMARY KEY (`DeliveryDocument`, `DeliveryDocumentItem`),
    
    CONSTRAINT `DPFMDeliveryDocumentItemData_fk` FOREIGN KEY (`DeliveryDocument`) REFERENCES `data_platform_delivery_document_header_data` (`DeliveryDocument`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataSCRDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_scr_delivery_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataSCRDeliveryPlantID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`) REFERENCES `data_platform_scr_delivery_plant_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataSCRStockConfPlantID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipStockConfPlantID`, `Buyer`, `Seller`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`) REFERENCES `data_platform_scr_stock_conf_plant_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipStockConfPlantID`, `Buyer`, `Seller`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataSCRProductionPlantID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`) REFERENCES `data_platform_scr_production_plant_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataSCRBillingID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`) REFERENCES `data_platform_scr_billing_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataSCRPaymentID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`) REFERENCES `data_platform_scr_payment_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`),
    -- CONSTRAINT `DPFMDeliveryDocumentItemDataSCRDeliveryPlantRelationProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`) REFERENCES `data_platform_scr_delivery_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`),　テーブルなし
    -- CONSTRAINT `DPFMDeliveryDocumentItemDataSCRStockConfPlantRelationProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipStockConfPlantID`, `Buyer`, `Seller`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `Product`) REFERENCES `data_platform_scr_stock_conf_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipStockConfPlantID`, `Buyer`, `Seller`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `Product`),　テーブルなし
    -- CONSTRAINT `DPFMDeliveryDocumentItemDataSCRProductionPlantRelationProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`) REFERENCES `data_platform_scr_production_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`),　テーブルなし
    CONSTRAINT `DPFMDeliveryDocumentItemDataProductGroup_fk` FOREIGN KEY (`ProductGroup`) REFERENCES `data_platform_product_group_product_group_data` (`ProductGroup`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataBillOfMaterial_fk` FOREIGN KEY (`BillOfMaterial`) REFERENCES `data_platform_bill_of_material_header_data` (`BillOfMaterial`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataBillOfMaterialItem_fk` FOREIGN KEY (`BillOfMaterial`, `BillOfMaterialItem`) REFERENCES `data_platform_bill_of_material_item_data` (`BillOfMaterial`, `BillOfMaterialItem`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataDeliveryUnit_fk` FOREIGN KEY (`DeliveryUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataItemWeightUnit_fk` FOREIGN KEY (`ItemWeightUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataInternalCapacityQuantityUnit_fk` FOREIGN KEY (`InternalCapacityQuantityUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataDeliverToPlantBatch_fk` FOREIGN KEY (`Product`, `DeliverToParty`, `DeliverToPlant`, `DeliverToPlantBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataDeliverFromPlantBatch_fk` FOREIGN KEY (`Product`, `DeliverFromParty`, `DeliverFromPlant`, `DeliverFromPlantBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataStockConfirmationPlantBatch_fk` FOREIGN KEY (`Product`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `StockConfirmationPlantBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataProductionPlantBatch_fk` FOREIGN KEY (`Product`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `ProductionPlantBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataDeliverToPlantStorageLocation_fk` FOREIGN KEY (`DeliverToParty`, `DeliverToPlant`, `DeliverToPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataDeliverFromPlantStorageLocation_fk` FOREIGN KEY (`DeliverFromParty`, `DeliverFromPlant`, `DeliverFromPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataProductionPlantStorageLocation_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`, `ProductionPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    -- CONSTRAINT `DPFMDeliveryDocumentItemDataInspectionPlan_fk` FOREIGN KEY (`InspectionPlan`) REFERENCES `data_platform_inspection_header_data` (`InspectionPlan`),　テーブルなし
    -- CONSTRAINT `DPFMDeliveryDocumentItemDataInspectionPlant_fk` FOREIGN KEY (`InspectionPlant`) REFERENCES `data_platform_plant_general_data` (`Plant`),  不明 
    CONSTRAINT `DPFMDeliveryDocumentItemDataOrderItem_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataProductionOrder_fk` FOREIGN KEY (`ProductionOrder`, `ProductionOrderItem`) REFERENCES `data_platform_production_order_item_data` (`ProductionOrder`, `ProductionOrderItem`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataOperations_fk` FOREIGN KEY (`Operations`, `OperationsItem`) REFERENCES `data_platform_production_operations_item_data` (`Operations`, `OperationsItem`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataBillOfMaterial_fk` FOREIGN KEY (`BillOfMaterial`, `BillOfMaterialItem`) REFERENCES `data_platform_production_bill_of_material_item_data` (`BillOfMaterial`, `BillOfMaterialItem`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataPaymentTerms_fk` FOREIGN KEY (`PaymentTerms`) REFERENCES `data_platform_payment_terms_payment_terms_data` (`PaymentTerms`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataPaymentMethod_fk` FOREIGN KEY (`PaymentMethod`) REFERENCES `data_platform_payment_method_payment_method_data` (`PaymentMethod`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataWBSElement_fk` FOREIGN KEY (`Project`, `WBSElement`) REFERENCES `data_platform_project_wbs_element_data` (`Project`, `WBSElement`),
    -- CONSTRAINT `DPFMDeliveryDocumentItemDataTaxCode_fk` FOREIGN KEY (`TaxCode`) REFERENCES `data_platform_tax_code_tax_code_data` (`TaxCode`),　不明
    CONSTRAINT `DPFMDeliveryDocumentItemDataCountryOfOrigin_fk` FOREIGN KEY (`CountryOfOrigin`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataCountryOfOriginLanguage_fk` FOREIGN KEY (`CountryOfOriginLanguage`) REFERENCES `data_platform_language_language_data` (`Language`),
    CONSTRAINT `DPFMDeliveryDocumentItemDataEquipment_fk` FOREIGN KEY (`Equipment`) REFERENCES `data_platform_equipment_master_general_data` (`Equipment`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
