CREATE TABLE `data_platform_delivery_document_item_data`
(
    `DeliveryDocument`                                int(16) NOT NULL,
    `DeliveryDocumentItem`                            int(6) NOT NULL,
    `DeliveryDocumentItemCategory`                    varchar(4) DEFAULT NULL,
    `SupplyChainRelationshipID`                       int(16) NOT NULL,
    `SupplyChainRelationshipDeliveryID`               int(6) NOT NULL,
    `SupplyChainRelationshipDeliveryPlantID`          int(4) NOT NULL,
    `SupplyChainRelationshipStockConfPlantID`         int(4) NOT NULL,
    `SupplyChainRelationshipProductionPlantID`        int(4) NOT NULL,
    `SupplyChainRelationshipBillingID`                int(4) DEFAULT NULL,
    `SupplyChainRelationshipPaymentID`                int(2) DEFAULT NULL,
    `Buyer`                                           int(12) NOT NULL,
    `Seller`                                          int(12) NOT NULL,
    `DeliverToParty`                                  int(12) NOT NULL,
    `DeliverFromParty`                                int(12) NOT NULL,
    `DeliverToPlant`                                  varchar(4) NOT NULL,
    `DeliverFromPlant`                                varchar(4) NOT NULL,
    `BillToParty`                                     int(12) DEFAULT NULL,
    `BillFromParty`                                   int(12) DEFAULT NULL,
    `BillToCountry`                                   varchar(3) DEFAULT NULL,
    `BillFromCountry`                                 varchar(3) DEFAULT NULL,
    `Payer`                                           int(12) DEFAULT NULL,
    `Payee`                                           int(12) DEFAULT NULL,
    `DeliverToPlantStorageLocation`                   varchar(4) DEFAULT NULL,
    `ProductIsBatchManagedInDeliverToPlant`           tinyint(1) DEFAULT NULL,
    `BatchMgmtPolicyInDeliverToPlant`                 varchar(4) DEFAULT NULL,
    `DeliverToPlantBatch`                             varchar(10) DEFAULT NULL,
    `DeliverToPlantBatchValidityStartDate`            date DEFAULT NULL,
    `DeliverToPlantBatchValidityEndDate`              date DEFAULT NULL,
    `DeliverFromPlantStorageLocation`                 varchar(4) DEFAULT NULL,
    `ProductIsBatchManagedInDeliverFromPlant`         tinyint(1) DEFAULT NULL,
    `BatchMgmtPolicyInDeliverFromPlant`               varchar(4) DEFAULT NULL,
    `DeliverFromPlantBatch`                           varchar(10) DEFAULT NULL,
    `DeliverFromPlantBatchValidityStartDate`          date DEFAULT NULL,
    `DeliverFromPlantBatchValidityEndDate`            date DEFAULT NULL,
    `StockConfirmationBusinessPartner`				  int(12) DEFAULT NULL,
    `StockConfirmationPlant`                          varchar(4) DEFAULT NULL,
    `ProductIsBatchManagedInStockConfirmationPlant`   tinyint(1) DEFAULT NULL,
    `BatchMgmtPolicyInStockConfirmationPlant`         varchar(4) DEFAULT NULL,
    `StockConfirmationPlantBatch`                     varchar(10) DEFAULT NULL,
    `StockConfirmationPlantBatchValidityStartDate`    date DEFAULT NULL,
    `StockConfirmationPlantBatchValidityEndDate`      date DEFAULT NULL,
    `StockConfirmationPolicy`                         varchar(4) DEFAULT NULL,
    `StockConfirmationStatus`                         varchar(2) DEFAULT NULL,
    `ProductionPlantBusinessPartner`				  int(12) DEFAULT NULL,
    `ProductionPlant`                                 varchar(4) DEFAULT NULL,
    `ProductionPlantStorageLocation`                  varchar(4) DEFAULT NULL,
    `ProductIsBatchManagedInProductionPlant`          tinyint(1) DEFAULT NULL,
    `BatchMgmtPolicyInProductionPlant`                varchar(4) DEFAULT NULL,
    `ProductionPlantBatch`                            varchar(10) DEFAULT NULL,
    `ProductionPlantBatchValidityStartDate`           date DEFAULT NULL,
    `ProductionPlantBatchValidityEndDate`             date DEFAULT NULL,
    `DeliveryDocumentItemText`                        varchar(200) DEFAULT NULL,
    `DeliveryDocumentItemTextByBuyer`                 varchar(200) NOT NULL,
    `DeliveryDocumentItemTextBySeller`                varchar(200) NOT NULL,
    `Product`                                         varchar(40) DEFAULT NULL,
    `ProductStandardID`                               varchar(18) DEFAULT NULL,
    `ProductGroup`                                    varchar(9) DEFAULT NULL,
    `BaseUnit`                                        varchar(3) DEFAULT NULL,
    `OriginalQuantityInBaseUnit`                      float(15) DEFAULT NULL,
    `DeliveryUnit`                                    varchar(3) DEFAULT NULL,
    `ActualGoodsIssueDate`                            date DEFAULT NULL,
    `ActualGoodsIssueTime`                            time DEFAULT NULL,
    `ActualGoodsReceiptDate`                          date DEFAULT NULL,
    `ActualGoodsReceiptTime`                          time DEFAULT NULL,
    `ActualGoodsIssueQtyInBaseUnit`                   float(15) DEFAULT NULL,
    `ActualGoodsIssueQuantity`                        float(15) DEFAULT NULL,
    `ActualGoodsReceiptQtyInBaseUnit`                 float(15) DEFAULT NULL,
    `ActualGoodsReceiptQuantity`                      float(15) DEFAULT NULL,
    `CreationDate`                                    date DEFAULT NULL,
    `CreationTime`                                    time DEFAULT NULL,
    `ItemBillingStatus`                               varchar(2) DEFAULT NULL,
    `ItemBillingConfStatus`                           varchar(2) DEFAULT NULL,
    `SalesCostGLAccount`                              varchar(10) DEFAULT NULL,
    `ReceivingGLAccount`                              varchar(10) DEFAULT NULL,
    `IssuingGoodsMovementType`                        varchar(3) DEFAULT NULL,
    `ReceivingGoodsMovementType`                      varchar(3) DEFAULT NULL,
    `ItemCompleteDeliveryIsDefined`                   tinyint(1) DEFAULT NULL,
    `ItemDeliveryIncompletionStatus`                  varchar(2) DEFAULT NULL,
    `ItemGrossWeight`                                 float(13) DEFAULT NULL,
    `ItemNetWeight`                                   float(13) DEFAULT NULL,
    `ItemWeightUnit`                                  varchar(3) DEFAULT NULL,
    `ItemIsBillingRelevant`                           tinyint(1) DEFAULT NULL,
    `LastChangeDate`                                  date DEFAULT NULL,
    `OrderID`                                         int(16) DEFAULT NULL,
    `OrderItem`                                       int(6) DEFAULT NULL,
    `OrderType`                                       varchar(3) DEFAULT NULL,
    `ContractType`                                    varchar(4) DEFAULT NULL,
    `OrderValidityStartDate`                          date DEFAULT NULL,
    `OrderValidityEndDate`                            date DEFAULT NULL,
    `PaymentTerms`                                    varchar(4) DEFAULT NULL,
    `DueCalculationBaseDate`                          date DEFAULT NULL,
    `PaymentDueDate`                                  date DEFAULT NULL,
    `NetPaymentDays`                                  int(3) DEFAULT NULL,
    `PaymentMethod`                                   varchar(1) DEFAULT NULL,
    `InvoicePeriodStartDate`                          date DEFAULT NULL,
    `InvoicePeriodEndDate`                            date DEFAULT NULL,
    `ConfirmedDeliveryDate`                           date DEFAULT NULL,
    `Project`                                         varchar(24) DEFAULT NULL,
--  `ProfitCenter`                                    varchar(10) DEFAULT NULL,
    `ReferenceDocument`                               int(16) DEFAULT NULL,
    `ReferenceDocumentItem`                           int(6) DEFAULT NULL,
    `TransactionTaxClassification`                    varchar(1) NOT NULL,
    `ProductTaxClassificationBillToCountry`           varchar(1) NOT NULL,
    `ProductTaxClassificationBillFromCountry`         varchar(1) NOT NULL,
    `DefinedTaxClassification`                        varchar(1) NOT NULL,
    `AccountAssignmentGroup`                          varchar(2) NOT NULL,
    `ProductAccountAssignmentGroup`                   varchar(2) NOT NULL,
    `TaxCode`                                         varchar(2) DEFAULT NULL,
    `TaxRate`                                         float(6) DEFAULT NULL,
    `CountryOfOrigin`                                 varchar(3) DEFAULT NULL,
    `CountryOfOriginLanguage`                         varchar(2) DEFAULT NULL,
    `StockIsFullyConfirmed`                           tinyint(1) DEFAULT NULL,
    `ItemDeliveryBlockStatus`                         tinyint(1) DEFAULT NULL,
    `ItemIssuingBlockStatus`                          tinyint(1) DEFAULT NULL,
    `ItemReceivingBlockStatus`                        tinyint(1) DEFAULT NULL,
    `ItemBillingBlockStatus`                          tinyint(1) DEFAULT NULL,
    
    PRIMARY KEY (`DeliveryDocument`, `DeliveryDocumentItem`),
    
    CONSTRAINT `DataPlatformDeliveryDocumentItemData_fk` FOREIGN KEY (`DeliveryDocument`) REFERENCES `data_platform_delivery_document_header_data` (`DeliveryDocument`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataSupplyChainRelationshipDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_supply_chain_relationship_delivery_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataSupplyChainRelationshipDeliveryPlantID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`) REFERENCES `data_platform_supply_chain_relationship_delivery_plant_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataSupplyChainRelationshipStockConfPlantID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipStockConfPlantID`, `Buyer`, `Seller`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`) REFERENCES `data_platform_supply_chain_relationship_stock_conf_plant_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipStockConfPlantID`, `Buyer`, `Seller`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataSupplyChainRelationshipProductionPlantID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`) REFERENCES `data_platform_supply_chain_relationship_production_plant_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataSupplyChainRelationshipBillingID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`) REFERENCES `data_platform_supply_chain_relationship_billing_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataSupplyChainRelationshipPaymentID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`) REFERENCES `data_platform_supply_chain_relationship_payment_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataSupplyChainRelationshipDeliveryPlantRelationProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`) REFERENCES `data_platform_supply_chain_relationship_delivery_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataSupplyChainRelationshipStockConfPlantRelationProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipStockConfPlantID`, `Buyer`, `Seller`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `Product`) REFERENCES `data_platform_supply_chain_relationship_stock_conf_plant_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipStockConfPlantID`, `Buyer`, `Seller`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `Product`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataSupplyChainRelationshipProductionPlantRelationProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`) REFERENCES `data_platform_supply_chain_relationship_production_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataProductGroup_fk` FOREIGN KEY (`ProductGroup`) REFERENCES `data_platform_product_group_product_group_data` (`ProductGroup`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit` (`QuantityUnit`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataDeliveryUnit_fk` FOREIGN KEY (`DeliveryUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit` (`QuantityUnit`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataItemWeightUnit_fk` FOREIGN KEY (`ItemWeightUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit` (`QuantityUnit`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataDeliverToPlantBatch_fk` FOREIGN KEY (`Product`, `DeliverToParty`, `DeliverToPlant`, `DeliverToPlantBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataDeliverFromPlantBatch_fk` FOREIGN KEY (`Product`, `DeliverFromParty`, `DeliverFromPlant`, `DeliverFromPlantBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataStockConfirmationPlantBatch_fk` FOREIGN KEY (`Product`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `StockConfirmationPlantBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataProductionPlantBatch_fk` FOREIGN KEY (`Product`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `ProductionPlantBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataDeliverToPlantStorageLocation_fk` FOREIGN KEY (`DeliverToParty`, `DeliverToPlant`, `DeliverToPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataDeliverFromPlantStorageLocation_fk` FOREIGN KEY (`DeliverFromParty`, `DeliverFromPlant`, `DeliverFromPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataProductionPlantStorageLocation_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`, `ProductionPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataOrderItem_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataPaymentTerms_fk` FOREIGN KEY (`PaymentTerms`) REFERENCES `data_platform_payment_terms_payment_terms_data` (`PaymentTerms`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataPaymentMethod_fk` FOREIGN KEY (`PaymentMethod`) REFERENCES `data_platform_payment_method_payment_method_data` (`PaymentMethod`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataTaxCode_fk` FOREIGN KEY (`TaxCode`) REFERENCES `data_platform_tax_code_tax_code_data` (`TaxCode`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataCountryOfOrigin_fk` FOREIGN KEY (`CountryOfOrigin`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DataPlatformDeliveryDocumentItemDataCountryOfOriginLanguage_fk` FOREIGN KEY (`CountryOfOriginLanguage`) REFERENCES `data_platform_language_language_data` (`Language`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
